"""Curve kinds (figforge/layers.py): error bars, shaded bands and bars are
built from table columns, drawn, exported as plain matplotlib and read back
from edited code -- and plain lines are exactly as before."""
import os as _os
ROOT_DIR = _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__)))
import copy, math, os, sys
sys.path.insert(0, ROOT_DIR)
os.chdir(ROOT_DIR)

from figforge import codegen, codesync, csvimport, layers, ops, render
from figforge.project import Figure, LocalStore

fails = []
def check(c, m): print(("PASS " if c else "FAIL ") + m); c or fails.append(m)

TEXT = "x,mean,err,lo,hi,count\n" + "\n".join(
    f"{i},{math.sin(i / 3):.4f},{0.1 + 0.02 * i:.3f},{math.sin(i / 3) - 0.3:.4f},"
    f"{math.sin(i / 3) + 0.3:.4f},{abs(int(10 * math.cos(i / 4)))}" for i in range(20)) + "\n"

spec, arrays = csvimport.build_panels("t", TEXT, [
    {"x": 0, "ys": [1], "kind": "line",
     "layers": [{"kind": "band", "y": 3, "extra": 4, "label": ""},
                {"kind": "errorbar", "y": 1, "extra": 2, "label": "data"}]},
    {"x": 0, "ys": [], "layers": [{"kind": "bar", "y": 5, "extra": None, "label": "histogram"}]}])
a, b = spec["panels"]
check([(s.get("kind", "line"), s["label"]) for s in a["series"]]
      == [("band", "lo – hi"), ("line", "mean"), ("errorbar", "data")],
      "bands go behind lines, error bars on top; a band is named by both edges")
err = a["series"][2]
check(err["yerr"] in arrays and abs(arrays[err["yerr"]][5] - 0.2) < 1e-9, "error column stored")
check(a["ylim"][0] < -1.3 and a["ylim"][1] > 1.29, "limits include the band and error bars")
check(b["ylim"][0] == 0.0 and abs(b["series"][0]["style"]["width"] - 0.8) < 1e-9,
      "bars stand on zero; width is 80% of the x spacing")
check(spec["source"]["panels"][0]["layers"][0]["kind"] == "band", "layers are kept for Start over")

try:
    csvimport.build_panels("t", TEXT, [{"x": 0, "ys": [], "layers": [{"kind": "band", "y": 3, "extra": 99}]}])
    check(False, "a band with a missing column is refused")
except csvimport.CSVError:
    check(True, "a band with a missing column is refused")

svg, _ = render.render(spec, arrays, preview=True)
check(all(f"t_{s['id']}" in svg for p in spec["panels"] for s in p["series"]),
      "every kind draws, with a click target")

code = codegen.generate(spec)
calls = [l.split("(")[0] for l in code.splitlines() if "gid='a_l" in l or "gid='b_l" in l]
check(sorted(calls) == ["ax.bar", "ax.errorbar", "ax.fill_between"], f"exported as plain matplotlib ({calls})")
check("figforge" not in code.split("HERE =")[0].lower().replace("generated by figforge", "")
      .replace("figforge's code editor", ""), "the export doesn't import FigForge")
back, rep = codesync.apply(code, spec, list(arrays))
check(back["panels"] == spec["panels"] and not rep["skipped"], "code -> figure round-trips exactly")

edited = code.replace("capsize=3", "capsize=6").replace("alpha=0.25", "alpha=0.5")
back, rep = codesync.apply(edited, spec, list(arrays))
sa = {s["id"]: s for s in back["panels"][0]["series"]}
check(sa["a_l1"]["style"]["capsize"] == 6 and sa["a_l0"]["style"]["alpha"] == 0.5,
      "style edits in code come back")
switched = code.replace('ax.bar(D["b_x"]', 'ax.plot(D["b_x"]').replace(", width=0.8", "")
assert switched != code
back, rep = codesync.apply(switched, spec, list(arrays))
bar = back["panels"][1]["series"][0]
check(bar.get("kind", "line") == "line" and "width" not in bar.get("style", {}) and not rep["skipped"],
      "turning ax.bar into ax.plot in code makes it a line")

# Plain lines: a figure from before kinds existed is untouched.
old = Figure("qcircle", LocalStore())
ospec, oarr = old.load_spec(), old.load_arrays()
check(all("kind" not in s for p in ospec["panels"] for s in p["series"]), "old figures have no kind field")
check(codesync.apply(codegen.generate(ospec), ospec, list(oarr))[0]["panels"] == ospec["panels"],
      "old figures round-trip unchanged")

# The editing tools see and restyle every kind.
d = ops.describe(spec, arrays)
check([c["kind"] for c in d["panels"][0]["curves"]] == ["band", "line", "errorbar"], "describe_figure names kinds")
new, res, _ = ops.apply(spec, [{"name": "style_series", "input": {
    "series_id": "b_l0", "color": "#2E8B57", "line_width": None, "line_style": "keep",
    "marker": "keep", "marker_size": None, "opacity": 0.5}}], arrays)
check(not res[0]["is_error"] and new["panels"][1]["series"][0]["style"]["alpha"] == 0.5,
      "style_series restyles bars")
render.render(new, arrays)
check(set(layers.KINDS) == {"line", "step", "errorbar", "band", "bar", "scatter", "heatmap",
                            "contour", "contourf", "box"}, "kinds table")

# Data + a fit on its own, finer grid, added later from a separate table.
NL = "\n"
data = "T,f_mean,f_std" + NL + NL.join(
    f"{t},{5.1 - 2e-5 * t * t:.6f},0.0002" for t in range(4, 31, 2)) + NL
fit = "T_fit,f_fit,ci_lo,ci_hi" + NL + NL.join(
    f"{t / 4},{5.1 - 2e-5 * (t / 4) ** 2:.6f},{5.1 - 2e-5 * (t / 4) ** 2 - 3e-4:.6f},"
    f"{5.1 - 2e-5 * (t / 4) ** 2 + 3e-4:.6f}" for t in range(16, 121)) + NL
fspec, farr = csvimport.build_panels("f", data, [{"x": "T", "ys": [], "layers": [
    {"kind": "errorbar", "y": "f_mean", "extra": "f_std"}]}])
check(fspec["source"]["panels"][0]["layers"][0]["y"] == "f_mean", "the recipe names columns, not positions")
fspec["panels"][0]["xlabel"]["text"] = "Temperature (K)"
merged, added = csvimport.merge_tables(data, fit)
check(added == ["T_fit", "f_fit", "ci_lo", "ci_hi"] and merged.count(NL) == 106, "a second table merges in")
nspec, narr, ids = csvimport.add_batch(fspec, "f", merged, "a", {"x": "T_fit", "ys": ["f_fit"], "kind": "line",
    "layers": [{"kind": "band", "y": "ci_lo", "extra": "ci_hi"}]})
p0 = nspec["panels"][0]
check([s.get("kind", "line") for s in p0["series"]] == ["band", "errorbar", "line"]
      and p0["series"][0]["x"] != p0["series"][1]["x"], "fit + band on their own x, band behind")
check(p0["xlabel"]["text"] == "Temperature (K)" and p0.get("legend"), "earlier edits are kept; a legend appears")
rspec, _ = csvimport.build_panels("f", merged, nspec["source"]["panels"])
check([s["id"] for s in rspec["panels"][0]["series"]] == [s["id"] for s in p0["series"]],
      "Start over rebuilds the added curves with the same ids")
render.render(nspec, narr)

# --- 2-D maps, coloured scatter, box plots, steps (from one tidy table) ---
import numpy as np
rng = np.random.RandomState(3)
gx, gy = np.linspace(0, 2, 25), np.linspace(-1, 1, 20)
rows = ["x,y,z,temp,size,sampleA,sampleB,t,signal"]
for i, (a_, b_) in enumerate((a_, b_) for b_ in gy for a_ in gx):
    z = np.exp(-((a_ - 1) ** 2 + b_ ** 2) * 3)
    sa = f"{rng.normal(1.0, 0.1):.4f}" if i < 60 else ""
    sb = f"{rng.normal(1.3, 0.2):.4f}" if i < 45 else ""
    t = f"{i * 0.1:.2f}" if i < 80 else ""
    sig = f"{np.sin(i * 0.2):.4f}" if i < 80 else ""
    rows.append(f"{a_:.4f},{b_:.4f},{z:.5f},{4 + i * 0.05:.3f},{rng.uniform(1, 5):.3f},{sa},{sb},{t},{sig}")
TBL = NL.join(rows) + NL
k2, a2 = csvimport.build_panels("k", TBL, [
    {"x": "x", "ys": [], "layers": [{"kind": "heatmap", "y": "y", "extra": "z"},
                                   {"kind": "contour", "y": "y", "extra": "z"}]},
    {"x": "", "ys": [], "layers": [{"kind": "box", "columns": ["sampleA", "sampleB"]}]},
    {"x": "temp", "ys": [], "layers": [{"kind": "scatter", "y": "z", "extra": "temp", "size": "size"}]},
    {"x": "t", "ys": ["signal"], "kind": "steps"}])
hm, ct = k2["panels"][0]["series"]
check(hm["kind"] == "heatmap" and a2[hm["z"]].shape == (20, 25) and hm.get("colorbar"),
      "tidy x, y, z columns become a gridded heatmap with a colour bar")
check(ct["style"].get("colors") == "white", "contours over a heatmap default to white lines")
check(abs(k2["panels"][0]["xlim"][0] - (-1 / 24)) < 1e-3, "a heatmap's axes hug its cell edges")
bx = k2["panels"][1]["series"][0]
check(bx["kind"] == "box" and len(a2[bx["groups"][0]]) == 60 and bx["style"]["tick_labels"] == ["sampleA", "sampleB"],
      "box plot: one group per column, blanks dropped, named on the axis")
sc = k2["panels"][2]["series"][0]
check(sc.get("c") and sc.get("sizes") and sc["colorbar"]["label"] == "temp", "scatter coloured and sized by columns")
check(k2["panels"][3]["series"][0]["kind"] == "step", "plot_as steps draws step lines")
svg2, _ = render.render(k2, a2, preview=True)
check(all(f"t_{s['id']}" in svg2 for p in k2["panels"] for s in p["series"]) and f"t_{hm['id']}__cbar" in svg2,
      "every new kind draws with a click target; the colour bar is clickable")
code2 = codegen.generate(k2)
check("_m = ax.pcolormesh(" in code2 and "fig.colorbar(_m, ax=ax)" in code2 and '_b["boxes"][0].set_gid(' in code2,
      "exported as plain matplotlib, colour bars included")
back2, rep2 = codesync.apply(code2, k2, list(a2))
check(back2["panels"] == k2["panels"] and not rep2["skipped"], "new kinds round-trip through code exactly")
nobar = NL.join(l for l in code2.split(NL) if not l.startswith("_cb"))
back3, _ = codesync.apply(nobar, k2, list(a2))
check("colorbar" not in back3["panels"][0]["series"][0], "deleting the colour bar lines in code removes the bar")
re2, _ = csvimport.build_panels("k", TBL, k2["source"]["panels"])
check(re2["panels"] == k2["panels"], "Start over rebuilds the new kinds identically")
new2, res2, _ = ops.apply(k2, [{"name": "style_colormap", "input": {
    "series_id": hm["id"], "colormap": "magma", "min": 0, "max": None, "log_scale": "keep",
    "colorbar": "keep", "colorbar_label": "I (a.u.)"}}], a2)
check(not res2[0]["is_error"] and new2["panels"][0]["series"][0]["style"]["cmap"] == "magma"
      and new2["panels"][0]["series"][0]["colorbar"]["label"] == "I (a.u.)", "style_colormap restyles a heatmap")
print(len(fails), "failure(s)")
