"""SPEC -> standalone matplotlib script.

The generated file is plain, readable matplotlib with every position and style
written out as a literal. It imports nothing from FigForge: drop it next to
data/curves.npz, run `python figure.py`, get the identical figure. That is what
"reproducible" means here (spec section 6.1).
"""

from figforge import layers

HEADER = '''r"""{title}

Generated by FigForge from spec.json, rev {rev}.

Standalone: needs only numpy + matplotlib and the curve arrays in
data/curves.npz. Edit freely. In FigForge's code editor, saving applies
your changes back to the draggable figure -- the gid='...' on each label,
curve and arrow is how it knows which one a line belongs to.
"""

import os

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrowPatch
from matplotlib.ticker import MultipleLocator

HERE = os.path.dirname(os.path.abspath(__file__))
D = np.load(os.path.join(HERE, "data", "curves.npz"))
'''


def _s(value):
    """Literal for a string, preferring a raw string when it reads better."""
    if isinstance(value, str):
        if "\\" in value and "'" not in value and "\n" not in value:
            return f"r'{value}'"
        return repr(value)
    return repr(value)


def _kw(mapping, skip=()):
    parts = []
    for k, v in mapping.items():
        if k in skip or v is None:
            continue
        parts.append(f"{k}={_s(v)}")
    return ", ".join(parts)


def _dict_literal(mapping):
    inner = ", ".join(f"{_s(k)}: {_s(v)}" for k, v in mapping.items())
    return "{" + inner + "}"


def _coord(ref):
    """Series coordinate: npz key or inline literals."""
    if isinstance(ref, str):
        return f'D["{ref}"]'
    return "[" + ", ".join(repr(round(float(v), 10)) for v in ref) + "]"



def _series_lines(s, axname="ax"):
    """One curve as matplotlib, from layers.KINDS. A colour-mapped curve with
    a colour bar is kept as _m for fig.colorbar; boxplot takes no gid, so
    its id goes on the first box."""
    k = layers.info(s)
    kind = layers.kind_of(s)
    args = [_coord(s[c]) for c in k["coords"]]
    args += ["[" + ", ".join(_coord(r) for r in s.get(f) or []) + "]" for f in k.get("lists", ())]
    args += [f"{kw}={_coord(s[f])}" for kw, f in k["data_kw"].items() if s.get(f) is not None]
    style = dict(k.get("fixed", {}))
    style.update(layers.style_for(s))
    kw = _kw(style)
    if kind in layers.LEGEND_KINDS and s.get("label"):
        kw = (kw + ", " if kw else "") + f"label={_s(s['label'])}"
    if kind != "box":
        kw = (kw + ", " if kw else "") + f"gid={_s(s['id'])}"
    cb = s.get("colorbar") if k.get("colorbar") else None
    target = "_b = " if kind == "box" else "_m = " if cb else ""
    out = [f"{target}{axname}.{k['method']}({', '.join(args)}" + (f", {kw}" if kw else "") + ")"]
    if kind == "box":
        out.append(f'_b["boxes"][0].set_gid({_s(s["id"])})')
    if cb:
        out.append("_cb = fig.colorbar(_m, ax=ax)")
        out.append(f"_cb.ax.tick_params(labelsize={cb.get('tick_size', 10)})")
        if cb.get("label"):
            out.append(f"_cb.set_label({_s(cb['label'])}, fontsize={cb.get('size', 12)}, "
                       f"color={_s(cb.get('color', 'black'))})")
    return out


def generate(spec):
    sup = spec.get("suptitle", {})
    L = [HEADER.format(
        title=sup.get("text", spec.get("figure_id", "figure")).replace('"""', ""),
        rev=spec.get("rev", 1),
    )]

    edits = {k: v for k, v in (spec.get("data_edits") or {}).items() if v}
    if edits:
        L.append("# Numbers changed by hand in FigForge (the data file still has the originals).")
        L.append("D = {k: D[k].copy() for k in D.files}")
        for key, rows in edits.items():
            for row, value in sorted(rows.items(), key=lambda kv: int(kv[0])):
                L.append(f'D["{key}"][{int(row)}] = {float(value)!r}')
        L.append("")

    rc = spec.get("rcparams", {})
    if rc:
        L.append("plt.rcParams.update({")
        for k, v in rc.items():
            L.append(f"    {_s(k)}: {_s(v)},")
        L.append("})\n")

    n = len(spec["panels"])
    w, h = spec["size_in"]
    rows, cols = _grid_shape(spec)
    # squeeze=False: axes is always a grid, so `axes[r, c]` works for one panel too
    L.append(f"fig, axes = plt.subplots({rows}, {cols}, figsize=({w}, {h}), squeeze=False)")
    if rows * cols > n:
        L.append(f"for _ax in axes.flat[{n}:]: _ax.remove()")
    L.append("fig.patch.set_facecolor('white')")
    if sup.get("text"):
        L.append(f"fig.suptitle({_s(sup['text'])}, fontsize={sup.get('size', 16)}, "
                 f"y={sup.get('y', 0.98)}, color={_s(sup.get('color', 'black'))})")
    L.append("")

    for i, p in enumerate(spec["panels"]):
        L.extend(_panel(p, i // cols, i % cols))

    layout = spec.get("layout", {})
    if layout.get("tight", True):
        L.append(f"fig.tight_layout(rect={layout.get('rect', [0, 0, 1, 1])})")
    L.append(f"fig.savefig(os.path.join(HERE, 'figure.png'), "
             f"dpi={spec.get('dpi', 200)}, facecolor='white')")
    L.append("plt.show()")
    return "\n".join(L) + "\n"


def _grid_shape(spec):
    n = len(spec["panels"])
    shape = spec.get("grid_shape")
    if shape and len(shape) == 2 and shape[0] * shape[1] >= n:
        return int(shape[0]), int(shape[1])
    return 1, n


def _panel(p, r, c):
    bar = "# " + "-" * 62 + f" ({p['id']})"
    L = [bar, f"ax = axes[{r}, {c}]"]

    for hl in p.get("hlines", []):
        L.append(f"ax.axhline({hl['y']!r}, color={_s(hl.get('color', '0.8'))}, "
                 f"ls={_s(hl.get('ls', '-'))}, lw={hl.get('lw', 1.0)})")
    for vl in p.get("vlines", []):
        L.append(f"ax.axvline({vl['x']!r}, color={_s(vl.get('color', '0.8'))}, "
                 f"ls={_s(vl.get('ls', '-'))}, lw={vl.get('lw', 1.0)})")
    if p.get("zero_lines"):
        L.append("ax.axhline(0, color='0.88', lw=0.7)")
        L.append("ax.axvline(0, color='0.88', lw=0.7)")

    for sp in p.get("spans", []):
        fn = "axvspan" if sp.get("axis", "x") == "x" else "axhspan"
        lbl = f", label={_s(sp['label'])}" if sp.get("label") else ""
        L.append(f"ax.{fn}({sp['lo']!r}, {sp['hi']!r}, color={_s(sp.get('color', '#cccccc'))}, "
                 f"alpha={sp.get('alpha', 0.25)!r}, lw=0, zorder=0.5{lbl})")
    twin = p.get("twin")
    if twin is not None:
        L.append("ax2 = ax.twinx()   # a second y-axis on the right, with its own data")
    for s in p.get("series", []):
        L += _series_lines(s, "ax2" if twin is not None and s.get("axis") == "right" else "ax")

    for a in p.get("arrows", []):
        L.append("ax.add_patch(FancyArrowPatch(")
        L.append(f"    ({a['p0'][0]!r}, {a['p0'][1]!r}), "
                 f"({a['p1'][0]!r}, {a['p1'][1]!r}),")
        L.append(f"    arrowstyle={_s(a.get('arrowstyle', '->'))}, "
                 f"mutation_scale={a.get('mutation_scale', 12)},")
        L.append(f"    lw={a.get('lw', 1.8)}, color={_s(a.get('color', 'black'))}, "
                 f"zorder={a.get('zorder', 6)}, gid={_s(a['id'])}))")

    for t in p.get("texts", []):
        args = [f"{t['xy'][0]!r}", f"{t['xy'][1]!r}", _s(t["text"])]
        kw = [f"fontsize={t.get('size', 12)}",
              f"color={_s(t.get('color', 'black'))}",
              f"ha={_s(t.get('ha', 'left'))}",
              f"va={_s(t.get('va', 'baseline'))}"]
        if t.get("coords", "data") == "axes":
            kw.append("transform=ax.transAxes")
        if t.get("bbox"):
            kw.append("bbox=" + _dict_literal(t["bbox"]))
        kw.append(f"zorder={t.get('zorder', 10)}")
        kw.append("clip_on=False")
        kw.append(f"gid={_s(t['id'])}")
        L.append(f"_t = ax.text({', '.join(args)},")
        L.append(f"        {', '.join(kw)})")
        if t.get("bbox"):
            L.append("_t.get_bbox_patch().set_clip_on(False)")

    title = p.get("title", {})
    if title.get("text"):
        L.append(f"ax.set_title({_s(title['text'])}, loc={_s(title.get('loc', 'center'))}, "
                 f"fontsize={title.get('size', 14)}, "
                 f"color={_s(title.get('color', 'black'))})")
    for key, fn in (("xlabel", "set_xlabel"), ("ylabel", "set_ylabel")):
        lab = p.get(key, {})
        if lab.get("text"):
            L.append(f"ax.{fn}({_s(lab['text'])}, fontsize={lab.get('size', 13)}, "
                     f"color={_s(lab.get('color', 'black'))})")

    if p.get("xscale", "linear") != "linear":
        L.append(f"ax.set_xscale({_s(p['xscale'])})")
    if p.get("yscale", "linear") != "linear":
        L.append(f"ax.set_yscale({_s(p['yscale'])})")
    L.append(f"ax.set_xlim({p['xlim'][0]!r}, {p['xlim'][1]!r})")
    L.append(f"ax.set_ylim({p['ylim'][0]!r}, {p['ylim'][1]!r})")
    if p.get("aspect", "auto") == "equal":
        L.append("ax.set_aspect('equal', 'datalim')" if p.get("twin") is not None else "ax.set_aspect('equal', 'box')")

    L.append(f'ax.tick_params(axis="x", labelsize={p.get("xtick_size", 11)})')
    L.append(f'ax.tick_params(axis="y", labelsize={p.get("ytick_size", 11)})')
    L.append(f"for _sp in ax.spines.values(): _sp.set_linewidth({p.get('frame_lw', 0.8)})")
    for xy in ("x", "y"):
        f = p.get(f"{xy}fmt") or {}
        if f.get("step"):
            L.append(f"ax.{xy}axis.set_major_locator(MultipleLocator({f['step']!r}))")
        if f.get("sci"):
            L.append(f"ax.ticklabel_format(axis={_s(xy)}, style='sci', scilimits=(0, 0))")
    if p.get("minor_ticks") or p.get("grid") == "both":
        L.append("ax.minorticks_on()")
    if p.get("grid"):
        L.append("ax.set_axisbelow(True)")
        L.append("ax.grid(True, which='major', color='0.85', lw=0.6)")
        if p["grid"] == "both":
            L.append("ax.grid(True, which='minor', color='0.93', lw=0.4)")
    if twin is not None:
        if twin.get("yscale", "linear") != "linear":
            L.append(f"ax2.set_yscale({_s(twin['yscale'])})")
        if twin.get("ylim"):
            L.append(f"ax2.set_ylim({twin['ylim'][0]!r}, {twin['ylim'][1]!r})")
        L.append(f'ax2.tick_params(axis="y", labelsize={twin.get("tick_size", p.get("ytick_size", 11))})')
        lab = p.get("ylabel2") or {}
        if lab.get("text"):
            L.append(f"ax2.set_ylabel({_s(lab['text'])}, fontsize={lab.get('size', 13)}, "
                     f"color={_s(lab.get('color', 'black'))})")
    for key, side, xy, var in (("top_axis", "top", "x", "_top"), ("right_axis", "right", "y", "_right")):
        sa = p.get(key)
        if not sa or (twin is not None and key == "right_axis"):
            continue
        a, b = sa["scale"], sa["offset"]
        L.append(f"# second scale on the {side}: {side} = {a!r} * {'bottom' if xy == 'x' else 'left'} + {b!r}")
        L.append(f"{var} = ax.secondary_{xy}axis({_s(side)}, functions=(lambda v: {a!r} * v + {b!r}, "
                 f"lambda v: (v - {b!r}) / {a!r}))")
        L.append(f"{var}.tick_params(labelsize={p.get(f'{xy}tick_size', 11)})")
        if sa.get("text"):
            L.append(f"{var}.set_{xy}label({_s(sa['text'])}, fontsize={sa.get('size', 13)}, "
                     f"color={_s(sa.get('color', 'black'))})")

    lg = p.get("legend")
    if lg and any(s.get("label") for s in p.get("series", [])):
        if lg.get('xy'):
            L.append(f"ax.legend(loc='upper left', "
                     f"bbox_to_anchor=({lg['xy'][0]!r}, {lg['xy'][1]!r}), "
                     f"bbox_transform=ax.transAxes, borderaxespad=0, "
                     f"frameon={lg.get('frameon', False)!r}, "
                     f"fontsize={lg.get('size', 10)})")
        else:
            L.append(f"ax.legend(loc={_s(lg.get('loc', 'best'))}, "
                     f"frameon={lg.get('frameon', False)!r}, "
                     f"fontsize={lg.get('size', 10)})")
    if twin is not None:   # one legend for the curves on both axes
        L = [l.replace("ax.legend(", "ax.legend(handles=ax.get_legend_handles_labels()[0] + "
                       "ax2.get_legend_handles_labels()[0], ", 1) if l.startswith("ax.legend(") else l
             for l in L]
    L.append("")
    return L
