"""SPEC -> standalone matplotlib script.

The generated file is plain, readable matplotlib with every position and style
written out as a literal. It imports nothing from FigForge: drop it next to
data/curves.npz, run `python figure.py`, get the identical figure. That is what
"reproducible" means here (spec section 6.1).
"""

import datetime

HEADER = '''r"""{title}

Generated by FigForge from spec.json (rev {rev}) on {stamp}.

Standalone: needs only numpy + matplotlib and the curve arrays in
data/curves.npz. Edit freely -- but note that regenerating from the editor
overwrites this file, so make lasting changes in the editor, not here.
"""

import os

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrowPatch

HERE = os.path.dirname(os.path.abspath(__file__))
D = np.load(os.path.join(HERE, "data", "curves.npz"))
'''


def _s(value):
    """Literal for a string, preferring a raw string when it reads better."""
    if isinstance(value, str):
        if "\\" in value and "'" not in value and "\n" not in value:
            return f"r'{value}'"
        return repr(value)
    return repr(value)


def _kw(mapping, skip=()):
    parts = []
    for k, v in mapping.items():
        if k in skip or v is None:
            continue
        parts.append(f"{k}={_s(v)}")
    return ", ".join(parts)


def _dict_literal(mapping):
    inner = ", ".join(f"{_s(k)}: {_s(v)}" for k, v in mapping.items())
    return "{" + inner + "}"


def _coord(ref):
    """Series coordinate: npz key or inline literals."""
    if isinstance(ref, str):
        return f'D["{ref}"]'
    return "[" + ", ".join(repr(round(float(v), 10)) for v in ref) + "]"


STYLE_KEYS = {"color", "lw", "linewidth", "ls", "linestyle", "marker", "ms",
              "markersize", "mew", "markeredgewidth", "mfc", "markerfacecolor",
              "mec", "markeredgecolor", "alpha", "zorder"}


def generate(spec):
    sup = spec.get("suptitle", {})
    L = [HEADER.format(
        title=sup.get("text", spec.get("figure_id", "figure")).replace('"""', ""),
        rev=spec.get("rev", 1),
        stamp=datetime.datetime.now().strftime("%Y-%m-%d %H:%M"),
    )]

    rc = spec.get("rcparams", {})
    if rc:
        L.append("plt.rcParams.update({")
        for k, v in rc.items():
            L.append(f"    {_s(k)}: {_s(v)},")
        L.append("})\n")

    n = len(spec["panels"])
    w, h = spec["size_in"]
    L.append(f"fig, axes = plt.subplots(1, {n}, figsize=({w}, {h}))")
    L.append("fig.patch.set_facecolor('white')")
    if sup.get("text"):
        L.append(f"fig.suptitle({_s(sup['text'])}, fontsize={sup.get('size', 16)}, "
                 f"y={sup.get('y', 0.98)}, color={_s(sup.get('color', 'black'))})")
    L.append("")

    for i, p in enumerate(spec["panels"]):
        L.extend(_panel(p, i))

    layout = spec.get("layout", {})
    if layout.get("tight", True):
        L.append(f"fig.tight_layout(rect={layout.get('rect', [0, 0, 1, 1])})")
    L.append(f"fig.savefig(os.path.join(HERE, 'figure.png'), "
             f"dpi={spec.get('dpi', 200)}, facecolor='white')")
    L.append("plt.show()")
    return "\n".join(L) + "\n"


def _panel(p, i):
    bar = "# " + "-" * 62 + f" ({p['id']})"
    L = [bar, f"ax = axes[{i}]"]

    for hl in p.get("hlines", []):
        L.append(f"ax.axhline({hl['y']!r}, color={_s(hl.get('color', '0.8'))}, "
                 f"ls={_s(hl.get('ls', '-'))}, lw={hl.get('lw', 1.0)})")
    for vl in p.get("vlines", []):
        L.append(f"ax.axvline({vl['x']!r}, color={_s(vl.get('color', '0.8'))}, "
                 f"ls={_s(vl.get('ls', '-'))}, lw={vl.get('lw', 1.0)})")
    if p.get("zero_lines"):
        L.append("ax.axhline(0, color='0.88', lw=0.7)")
        L.append("ax.axvline(0, color='0.88', lw=0.7)")

    for s in p.get("series", []):
        style = {k: v for k, v in (s.get("style") or {}).items() if k in STYLE_KEYS}
        kw = _kw(style)
        if s.get("label"):
            kw = (kw + ", " if kw else "") + f"label={_s(s['label'])}"
        L.append(f"ax.plot({_coord(s['x'])}, {_coord(s['y'])}"
                 + (f", {kw}" if kw else "") + ")")

    for a in p.get("arrows", []):
        L.append("ax.add_patch(FancyArrowPatch(")
        L.append(f"    ({a['p0'][0]!r}, {a['p0'][1]!r}), "
                 f"({a['p1'][0]!r}, {a['p1'][1]!r}),")
        L.append(f"    arrowstyle={_s(a.get('arrowstyle', '->'))}, "
                 f"mutation_scale={a.get('mutation_scale', 12)},")
        L.append(f"    lw={a.get('lw', 1.8)}, color={_s(a.get('color', 'black'))}, "
                 f"zorder={a.get('zorder', 6)}))")

    for t in p.get("texts", []):
        args = [f"{t['xy'][0]!r}", f"{t['xy'][1]!r}", _s(t["text"])]
        kw = [f"fontsize={t.get('size', 12)}",
              f"color={_s(t.get('color', 'black'))}",
              f"ha={_s(t.get('ha', 'left'))}",
              f"va={_s(t.get('va', 'baseline'))}"]
        if t.get("coords", "data") == "axes":
            kw.append("transform=ax.transAxes")
        if t.get("bbox"):
            kw.append("bbox=" + _dict_literal(t["bbox"]))
        kw.append(f"zorder={t.get('zorder', 10)}")
        L.append(f"ax.text({', '.join(args)},")
        L.append(f"        {', '.join(kw)})")

    title = p.get("title", {})
    if title.get("text"):
        L.append(f"ax.set_title({_s(title['text'])}, loc={_s(title.get('loc', 'center'))}, "
                 f"fontsize={title.get('size', 14)}, "
                 f"color={_s(title.get('color', 'black'))})")
    for key, fn in (("xlabel", "set_xlabel"), ("ylabel", "set_ylabel")):
        lab = p.get(key, {})
        if lab.get("text"):
            L.append(f"ax.{fn}({_s(lab['text'])}, fontsize={lab.get('size', 13)}, "
                     f"color={_s(lab.get('color', 'black'))})")

    if p.get("xscale", "linear") != "linear":
        L.append(f"ax.set_xscale({_s(p['xscale'])})")
    if p.get("yscale", "linear") != "linear":
        L.append(f"ax.set_yscale({_s(p['yscale'])})")
    L.append(f"ax.set_xlim({p['xlim'][0]!r}, {p['xlim'][1]!r})")
    L.append(f"ax.set_ylim({p['ylim'][0]!r}, {p['ylim'][1]!r})")
    if p.get("aspect", "auto") == "equal":
        L.append("ax.set_aspect('equal', 'box')")

    lg = p.get("legend")
    if lg and any(s.get("label") for s in p.get("series", [])):
        L.append(f"ax.legend(loc={_s(lg.get('loc', 'best'))}, "
                 f"frameon={lg.get('frameon', False)!r}, "
                 f"fontsize={lg.get('size', 10)})")
    L.append("")
    return L
