r"""$2\,\mathrm{K}$ Nb-plated Cu cavity

Generated by FigForge from spec.json (rev 1) on 2026-09-02 16:37.

Standalone: needs only numpy + matplotlib and the curve arrays in
data/curves.npz. Edit freely -- but note that regenerating from the editor
overwrites this file, so make lasting changes in the editor, not here.
"""

import os

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrowPatch

HERE = os.path.dirname(os.path.abspath(__file__))
D = np.load(os.path.join(HERE, "data", "curves.npz"))

plt.rcParams.update({
    'font.size': 12,
    'xtick.labelsize': 11,
    'ytick.labelsize': 11,
})

fig, axes = plt.subplots(1, 3, figsize=(16.2, 5.35))
fig.patch.set_facecolor('white')
fig.suptitle(r'$2\,\mathrm{K}$ Nb-plated Cu cavity', fontsize=18, y=0.98, color='#000000')

# -------------------------------------------------------------- (a)
ax = axes[0]
ax.axhline(0, color='0.88', lw=0.7)
ax.axvline(0, color='0.88', lw=0.7)
ax.plot(D["S11_re"], D["S11_im"], ls='none', marker='.', color='#4C78A8', ms=3.0, alpha=0.75, label='measured')
ax.plot(D["fit11_re"], D["fit11_im"], color='#E07A3D', lw=2.2, label='circle fit')
ax.plot([0.0], [0.0], ls='none', marker='+', color='black', ms=16, mew=2.0, zorder=7)
ax.plot([-0.1421865575], [0.0130738894], ls='none', marker='o', color='black', ms=6, zorder=7)
ax.plot([-0.0670826116], [0.0061681685], ls='none', marker='s', color='#2E8B57', ms=7, zorder=8)
ax.plot([0.0, -0.1421865575], [0.0, 0.0130738894], color='black', ls='--', lw=1.2)
ax.add_patch(FancyArrowPatch(
    (-0.14218655750048398, 0.013073889355671244), (-0.06708261156308878, 0.00616816847304507),
    arrowstyle='<->', mutation_scale=12,
    lw=1.8, color='#2E8B57', zorder=6))
ax.add_patch(FancyArrowPatch(
    (-0.0016481267084024825, -0.017924387809714743), (-0.21893863014628165, 0.002055222428582675),
    arrowstyle='->', mutation_scale=12,
    lw=1.8, color='#1f4e8c', zorder=6))
_t = ax.text(-0.248, 0.108, r'$\beta_1=0.53$',
        fontsize=12, color='#000000', ha='left', va='baseline', bbox={'boxstyle': 'round,pad=0.25', 'fc': 'white', 'ec': '#E07A3D', 'lw': 1.3}, zorder=10, clip_on=False)
_t.get_bbox_patch().set_clip_on(False)
_t = ax.text(-0.205, 0.055, '$R=0.075$',
        fontsize=11, color='#2E8B57', ha='left', va='baseline', zorder=10, clip_on=False)
_t = ax.text(-0.095, 0.055, '$|C|=0.14$',
        fontsize=11, color='#262626', ha='left', va='baseline', zorder=10, clip_on=False)
_t = ax.text(0.005, 0.012, 'origin',
        fontsize=10, color='#333333', ha='left', va='baseline', zorder=10, clip_on=False)
_t = ax.text(-0.12, -0.038, r'$|\Gamma_\mathrm{off}|=|C|+R=0.22$',
        fontsize=10, color='#1f4e8c', ha='left', va='baseline', bbox={'boxstyle': 'round,pad=0.2', 'fc': 'white', 'ec': '#1f4e8c', 'lw': 1.0}, zorder=10, clip_on=False)
_t.get_bbox_patch().set_clip_on(False)
_t = ax.text(-0.248, -0.108, '$d=2R/|\\Gamma_\\mathrm{off}|=0.15/0.22$\n$\\beta=d/(2-d)=0.53$',
        fontsize=10, color='#000000', ha='left', va='baseline', bbox={'boxstyle': 'round,pad=0.25', 'fc': 'white', 'ec': '#999999', 'lw': 0.8}, zorder=10, clip_on=False)
_t.get_bbox_patch().set_clip_on(False)
ax.set_title('(a) drive port — $S_{11}$', loc='left', fontsize=14, color='#000000')
ax.set_xlabel('Re $S_{11}$', fontsize=13, color='#000000')
ax.set_ylabel('Im $S_{11}$', fontsize=13, color='#000000')
ax.set_xlim(-0.26, 0.05)
ax.set_ylim(-0.12, 0.13)
ax.set_aspect('equal', 'box')
ax.legend(loc='lower right', frameon=False, fontsize=10)

# -------------------------------------------------------------- (b)
ax = axes[1]
ax.axhline(0, color='0.88', lw=0.7)
ax.axvline(0, color='0.88', lw=0.7)
ax.plot(D["S33_re"], D["S33_im"], ls='none', marker='.', color='#4C78A8', ms=3.0, alpha=0.75, label='measured')
ax.plot(D["fit33_re"], D["fit33_im"], color='#E07A3D', lw=2.2, label='circle fit')
ax.plot([0.0], [0.0], ls='none', marker='+', color='black', ms=16, mew=2.0, zorder=7)
ax.plot([-0.0054960318], [-0.206098702], ls='none', marker='o', color='black', ms=6, zorder=7)
ax.plot([-0.0041862687], [-0.1569831816], ls='none', marker='s', color='#2E8B57', ms=7, zorder=8)
ax.plot([0.0, -0.0054960318], [0.0, -0.206098702], color='black', ls='--', lw=1.2)
ax.add_patch(FancyArrowPatch(
    (-0.005496031773808749, -0.20609870199466968), (-0.0041862687433424075, -0.15698318163212102),
    arrowstyle='<->', mutation_scale=12,
    lw=1.8, color='#2E8B57', zorder=6))
ax.add_patch(FancyArrowPatch(
    (-0.012, 0.0), (-0.01880579480427509, -0.25521422235721836),
    arrowstyle='<->', mutation_scale=12,
    lw=1.8, color='#1f4e8c', zorder=6))
_t = ax.text(-0.148, 0.018, r'$\beta_2=0.24$',
        fontsize=12, color='#000000', ha='left', va='baseline', bbox={'boxstyle': 'round,pad=0.25', 'fc': 'white', 'ec': '#E07A3D', 'lw': 1.3}, zorder=10, clip_on=False)
_t.get_bbox_patch().set_clip_on(False)
_t = ax.text(0.018, 0.01, 'origin',
        fontsize=10, color='#333333', ha='left', va='baseline', zorder=10, clip_on=False)
_t = ax.text(0.018, -0.1, '$|C|=0.21$',
        fontsize=11, color='#262626', ha='left', va='baseline', zorder=10, clip_on=False)
_t = ax.text(0.018, -0.175, '$R=0.049$',
        fontsize=11, color='#2E8B57', ha='left', va='baseline', zorder=10, clip_on=False)
_t = ax.text(-0.148, -0.145, '$|\\Gamma_\\mathrm{off}|$\n$=0.26$',
        fontsize=10, color='#1f4e8c', ha='left', va='baseline', bbox={'boxstyle': 'round,pad=0.2', 'fc': 'white', 'ec': '#1f4e8c', 'lw': 1.0}, zorder=10, clip_on=False)
_t.get_bbox_patch().set_clip_on(False)
_t = ax.text(-0.148, -0.292, '$d=2R/|\\Gamma_\\mathrm{off}|=0.10/0.26$\n$\\beta=d/(2-d)=0.24$',
        fontsize=10, color='#000000', ha='left', va='baseline', bbox={'boxstyle': 'round,pad=0.25', 'fc': 'white', 'ec': '#999999', 'lw': 0.8}, zorder=10, clip_on=False)
_t.get_bbox_patch().set_clip_on(False)
ax.set_title('(b) pickup port — $S_{33}$', loc='left', fontsize=14, color='#000000')
ax.set_xlabel('Re $S_{33}$', fontsize=13, color='#000000')
ax.set_ylabel('Im $S_{33}$', fontsize=13, color='#000000')
ax.set_xlim(-0.16, 0.14)
ax.set_ylim(-0.31, 0.04)
ax.set_aspect('equal', 'box')
ax.legend(loc='lower right', frameon=False, fontsize=10)

# -------------------------------------------------------------- (c)
ax = axes[2]
ax.axhline(0.5, color='#cccccc', ls=':', lw=0.8)
ax.axvline(-6.221435998916626, color='#E07A3D', ls=':', lw=1.1)
ax.axvline(0.0, color='#E07A3D', ls=':', lw=1.1)
ax.axvline(5.680441999435425, color='#E07A3D', ls=':', lw=1.1)
ax.plot(D["df_kHz"], D["P_norm"], ls='none', marker='.', color='#4C78A8', ms=3.0, label='measured')
ax.plot(D["df_kHz"], D["lorentzian"], color='#E07A3D', lw=2.2, label='Lorentzian fit')
ax.plot([-6.2214359989, 5.6804419994], [0.5, 0.5], color='#E07A3D', lw=1.6)
ax.plot([-6.2214359989], [0.5], ls='none', marker='D', color='#E07A3D', ms=5)
ax.plot([5.6804419994], [0.5], ls='none', marker='D', color='#E07A3D', ms=5)
ax.plot([0.0], [1.0], ls='none', marker='o', color='#E07A3D', ms=7)
ax.add_patch(FancyArrowPatch(
    (-6.221435998916626, 0.5), (5.680441999435425, 0.5),
    arrowstyle='<->', mutation_scale=10,
    lw=1.6, color='#E07A3D', zorder=6))
_t = ax.text(1.6, 0.56, r'$\Delta f$',
        fontsize=12, color='#E07A3D', ha='left', va='baseline', zorder=10, clip_on=False)
_t = ax.text(-6.221435998916626, 1.08, '$f_1$',
        fontsize=12, color='#E07A3D', ha='center', va='baseline', zorder=10, clip_on=False)
_t = ax.text(0.0, 1.08, '$f_0$',
        fontsize=12, color='#E07A3D', ha='center', va='baseline', zorder=10, clip_on=False)
_t = ax.text(5.680441999435425, 1.08, '$f_2$',
        fontsize=12, color='#E07A3D', ha='center', va='baseline', zorder=10, clip_on=False)
_t = ax.text(-38, 1.02, r'$Q_L=929\,\mathrm{k}$',
        fontsize=12, color='#000000', ha='left', va='baseline', bbox={'boxstyle': 'round,pad=0.25', 'fc': 'white', 'ec': '#E07A3D', 'lw': 1.3}, zorder=10, clip_on=False)
_t.get_bbox_patch().set_clip_on(False)
_t = ax.text(-38, 0.08, '$Q_0=Q_L(1+\\beta_1+\\beta_2)$\n$=929\\mathrm{k}\\times1.77=1.64\\mathrm{M}$',
        fontsize=10, color='#000000', ha='left', va='baseline', bbox={'boxstyle': 'round,pad=0.25', 'fc': 'white', 'ec': '#999999', 'lw': 0.8}, zorder=10, clip_on=False)
_t.get_bbox_patch().set_clip_on(False)
ax.set_title('(c) transmission — $S_{31}$', loc='left', fontsize=14, color='#000000')
ax.set_xlabel('frequency offset (kHz)', fontsize=13, color='#000000')
ax.set_ylabel('$|S_{31}|^2$ (norm. to peak)', fontsize=13, color='#000000')
ax.set_xlim(-40, 40)
ax.set_ylim(-0.06, 1.16)
ax.legend(loc='lower right', frameon=False, fontsize=10)

fig.tight_layout(rect=[0, 0, 1, 0.96])
fig.savefig(os.path.join(HERE, 'figure.png'), dpi=170, facecolor='white')
plt.show()
