r"""

Generated by FigForge from spec.json, rev 85.

Standalone: needs only numpy + matplotlib and the curve arrays in
data/curves.npz. Edit freely. In FigForge's code editor, saving applies
your changes back to the draggable figure -- the gid='...' on each label,
curve and arrow is how it knows which one a line belongs to.
"""

import os

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrowPatch

HERE = os.path.dirname(os.path.abspath(__file__))
D = np.load(os.path.join(HERE, "data", "curves.npz"))

plt.rcParams.update({
    'font.size': 12,
    'xtick.labelsize': 11,
    'ytick.labelsize': 11,
})

fig, axes = plt.subplots(1, 3, figsize=(16.2, 5.35), squeeze=False)
fig.patch.set_facecolor('white')

# -------------------------------------------------------------- (a)
ax = axes[0, 0]
ax.axhline(0, color='0.88', lw=0.7)
ax.axvline(0, color='0.88', lw=0.7)
ax.plot(D["S11_re"], D["S11_im"], ls='none', marker='.', color='#4C78A8', ms=10, alpha=1, label='measured', gid='a_meas')
ax.plot(D["fit11_re"], D["fit11_im"], color='#E07A3D', lw=2.2, alpha=1, label='circle fit', gid='a_fit')
ax.plot([0.0], [0.0], ls='none', marker='+', color='black', ms=16, mew=2, zorder=7, gid='a_origin')
ax.plot([-0.1421865575], [0.0130738894], ls='none', marker='o', color='black', ms=6, zorder=7, gid='a_center')
ax.plot([0.0, -0.1421865575], [0.0, 0.0130738894], color='black', ls='--', lw=1.2, gid='a_cline')
_t = ax.text(-0.2531, 0.11225, r'$\beta_1=0.53$',
        fontsize=12, color='#000000', ha='left', va='baseline', bbox={'boxstyle': 'round,pad=0.25', 'fc': 'white', 'ec': '#E07A3D', 'lw': 1.3}, zorder=10, clip_on=False, gid='a_beta1')
_t.get_bbox_patch().set_clip_on(False)
_t = ax.text(0.005, 0.012, 'origin',
        fontsize=10, color='#333333', ha='left', va='baseline', zorder=10, clip_on=False, gid='a_origin_lbl')
ax.set_title('(a) drive port — $S_{11}$', loc='left', fontsize=14, color='#000000')
ax.set_xlabel('Re $S_{11}$', fontsize=13, color='#000000')
ax.set_ylabel('Im $S_{11}$', fontsize=13, color='#000000')
ax.set_xlim(-0.26, 0.05)
ax.set_ylim(-0.12, 0.13)
ax.set_aspect('equal', 'box')
ax.tick_params(axis="x", labelsize=11)
ax.tick_params(axis="y", labelsize=11)
for _sp in ax.spines.values(): _sp.set_linewidth(0.8)
ax.legend(loc='lower right', frameon=False, fontsize=10)

# -------------------------------------------------------------- (b)
ax = axes[0, 1]
ax.axhline(0, color='0.88', lw=0.7)
ax.axvline(0, color='0.88', lw=0.7)
ax.plot(D["S33_re"], D["S33_im"], ls='none', marker='.', color='#4C78A8', ms=10, alpha=1, label='measured', gid='b_meas')
ax.plot(D["fit33_re"], D["fit33_im"], color='#E07A3D', lw=2.2, alpha=1, label='circle fit', gid='b_fit')
ax.plot([0.0], [0.0], ls='none', marker='+', color='black', ms=16, mew=2, zorder=7, gid='b_origin')
ax.plot([-0.0054960318], [-0.206098702], ls='none', marker='o', color='black', ms=6, zorder=7, gid='b_center')
ax.plot([0.0, -0.0054960318], [0.0, -0.206098702], color='black', ls='--', lw=1.2, gid='b_cline')
_t = ax.text(-0.148, 0.018, r'$\beta_2=0.24$',
        fontsize=12, color='#000000', ha='left', va='baseline', bbox={'boxstyle': 'round,pad=0.25', 'fc': 'white', 'ec': '#E07A3D', 'lw': 1.3}, zorder=10, clip_on=False, gid='b_beta2')
_t.get_bbox_patch().set_clip_on(False)
_t = ax.text(0.018, 0.01, 'origin',
        fontsize=10, color='#333333', ha='left', va='baseline', zorder=10, clip_on=False, gid='b_origin_lbl')
ax.set_title('(b) pickup port — $S_{22}$', loc='left', fontsize=14, color='#000000')
ax.set_xlabel('Re $S_{22}$', fontsize=13, color='#000000')
ax.set_ylabel('Im $S_{22}$', fontsize=13, color='#000000')
ax.set_xlim(-0.16, 0.14)
ax.set_ylim(-0.31, 0.04)
ax.set_aspect('equal', 'box')
ax.tick_params(axis="x", labelsize=11)
ax.tick_params(axis="y", labelsize=11)
for _sp in ax.spines.values(): _sp.set_linewidth(0.8)
ax.legend(loc='lower right', frameon=False, fontsize=10)

# -------------------------------------------------------------- (c)
ax = axes[0, 2]
ax.axhline(0.5, color='#cccccc', ls=':', lw=0.8)
ax.axvline(-6.221435998916626, color='#E07A3D', ls=':', lw=1.1)
ax.axvline(0, color='#E07A3D', ls=':', lw=1.1)
ax.axvline(5.680441999435425, color='#E07A3D', ls=':', lw=1.1)
ax.plot(D["df_kHz"], D["P_norm"], ls='none', marker='.', color='#4C78A8', ms=10, label='measured', gid='c_meas')
ax.plot(D["df_kHz"], D["lorentzian"], color='#E07A3D', lw=2.2, alpha=1, label='Lorentzian fit', gid='c_fit')
ax.plot([-6.2214359989, 5.6804419994], [0.5, 0.5], color='#E07A3D', lw=1.6, gid='c_halfline')
ax.plot([-6.2214359989], [0.5], ls='none', marker='D', color='#E07A3D', ms=5, gid='c_m1')
ax.plot([5.6804419994], [0.5], ls='none', marker='D', color='#E07A3D', ms=5, gid='c_m2')
ax.plot([0.0], [1.0], ls='none', marker='o', color='#E07A3D', ms=7, gid='c_peak')
ax.add_patch(FancyArrowPatch(
    (-6.221435998916626, 0.5), (5.680441999435425, 0.5),
    arrowstyle='<->', mutation_scale=10,
    lw=1.6, color='#E07A3D', zorder=6, gid='c_df_arrow'))
_t = ax.text(8.616, 0.5323, r'$\Delta f$',
        fontsize=12, color='#E07A3D', ha='left', va='baseline', zorder=10, clip_on=False, gid='c_deltaf')
_t = ax.text(-6.221, 1.08, '$f_1$',
        fontsize=12, color='#E07A3D', ha='center', va='baseline', bbox={'boxstyle': 'round,pad=0.05', 'fc': 'white', 'ec': 'white', 'lw': 0.8}, zorder=10, clip_on=False, gid='c_f1')
_t.get_bbox_patch().set_clip_on(False)
_t = ax.text(0, 1.08, '$f_0$',
        fontsize=12, color='#E07A3D', ha='center', va='baseline', bbox={'boxstyle': 'round,pad=0.05', 'fc': 'white', 'ec': 'white', 'lw': 0.8}, zorder=10, clip_on=False, gid='c_f0')
_t.get_bbox_patch().set_clip_on(False)
_t = ax.text(5.941, 1.08, '$f_2$',
        fontsize=12, color='#E07A3D', ha='center', va='baseline', bbox={'boxstyle': 'round,pad=0.05', 'fc': 'white', 'ec': 'white', 'lw': 0.8}, zorder=10, clip_on=False, gid='c_f2')
_t.get_bbox_patch().set_clip_on(False)
_t = ax.text(-38.22, 1.0832, r'$Q_0=1.64\,\mathrm{M}$',
        fontsize=12, color='#000000', ha='left', va='baseline', bbox={'boxstyle': 'round,pad=0.25', 'fc': 'white', 'ec': '#E07A3D', 'lw': 1.3}, zorder=10, clip_on=False, gid='c_QL')
_t.get_bbox_patch().set_clip_on(False)
ax.set_title('(c) transmission — $S_{21}$', loc='left', fontsize=14, color='#000000')
ax.set_xlabel('frequency offset (kHz)', fontsize=13, color='#000000')
ax.set_ylabel('$|S_{21}|^2$ (norm. to peak)', fontsize=13, color='#000000')
ax.set_xlim(-40, 40)
ax.set_ylim(-0.06, 1.16)
ax.tick_params(axis="x", labelsize=11)
ax.tick_params(axis="y", labelsize=11)
for _sp in ax.spines.values(): _sp.set_linewidth(0.8)
ax.legend(loc='upper left', bbox_to_anchor=(0.6622, 0.1262), bbox_transform=ax.transAxes, borderaxespad=0, frameon=False, fontsize=10)

fig.tight_layout(rect=[0, 0, 1, 0.96])
fig.savefig(os.path.join(HERE, 'figure.png'), dpi=170, facecolor='white')
plt.show()
